"""Added many to many relationship between teams and players

Revision ID: 006e1858da16
Revises: d6e641c9b28d
Create Date: 2023-10-09 23:47:18.740092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006e1858da16'
down_revision = 'd6e641c9b28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_teams',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_players_teams_player_id_player')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_players_teams_team_id_team')),
    sa.PrimaryKeyConstraint('player_id', 'team_id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_team_id_team', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_player_team_id_team', 'team', ['team_id'], ['id'])

    op.drop_table('players_teams')
    # ### end Alembic commands ###
