"""Deleted time in game model

Revision ID: 347b6cbf1d05
Revises: 7776e7a57f61
Create Date: 2023-10-07 16:46:37.379051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347b6cbf1d05'
down_revision = '7776e7a57f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
