"""Added team foreignkey to player and staff models

Revision ID: 8c13d44da0b6
Revises: d62f5bc1e570
Create Date: 2023-10-07 16:35:18.965502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c13d44da0b6'
down_revision = 'd62f5bc1e570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_players_team_id_teams'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_staff_team_id_teams'), 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_staff_team_id_teams'), type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_players_team_id_teams'), type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
