"""Deleted time attribute

Revision ID: cffe4d17c79d
Revises: 282bd02b7690
Create Date: 2023-10-07 16:56:27.392005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffe4d17c79d'
down_revision = '282bd02b7690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
