"""3rd revision

Revision ID: d62f5bc1e570
Revises: 05fa7762f6a9
Create Date: 2023-10-07 16:31:33.220042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62f5bc1e570'
down_revision = '05fa7762f6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_players')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_players_team_id_teams', type_='foreignkey')
        batch_op.drop_constraint('fk_players_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_players_profile_id_profiles'), 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('team_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_staff_team_id_teams', type_='foreignkey')
        batch_op.drop_constraint('fk_staff_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_staff_profile_id_profiles'), 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('team_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_profile_id', ['profile_id'])
        batch_op.drop_constraint('fk_users_player_id_players', type_='foreignkey')
        batch_op.drop_constraint('fk_users_staff_id_staff', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_profile_id_profiles'), 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('player_id')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_profile_id_profiles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_staff_id_staff', 'staff', ['staff_id'], ['id'])
        batch_op.create_foreign_key('fk_users_player_id_players', 'players', ['player_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_staff_profile_id_profiles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_staff_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_staff_team_id_teams', 'teams', ['team_id'], ['id'])
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_players_profile_id_profiles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_players_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_players_team_id_teams', 'teams', ['team_id'], ['id'])
        batch_op.drop_column('profile_id')

    op.create_table('_alembic_tmp_players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('jersey_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='fk_players_profile_id_profiles'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
