"""created a team table and deleted many to many relationship of league and users"


Revision ID: d6e641c9b28d
Revises: 16922ad298ef
Create Date: 2023-10-09 17:32:20.503147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e641c9b28d'
down_revision = '16922ad298ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_player_team_id_team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_player_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_league_association')
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_constraint('fk_league_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_team_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_team_league_id_league'), 'league', ['league_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_team_league_id_league'), type_='foreignkey')
        batch_op.create_foreign_key('fk_team_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('league_id')

    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_league_user_id_user', 'user', ['user_id'], ['id'])

    op.create_table('user_league_association',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], name='fk_user_league_association_league_id_league'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_league_association_user_id_user')
    )
    op.drop_table('player')
    # ### end Alembic commands ###
